### ISSUE TITLE
suggest: complete the docs

### ISSUE THREAD

**Issue by sinkcup** [tbleckert/react-select-search#1]
I have read the docs, but can't find how to import and option's format.

maybe like this:

```
import SelectSearch from 'react-select-search';

const options = [{name: 'Sweden', value: 'SE'}, {name: 'Italy', value: 'IT'}];

render() {
  return (
    <SelectSearch name="country" options={options} value="SE" />
  );
}
```

**Comment by tbleckert** [comment]
Great suggestion! Will definitely focus on that, I'll keep you posted.

**Comment by tbleckert** [comment]
Oh and also, you're doing it right @sinkcup . Keep in mind that you can add any keys and values you want to the option and use those in the different callbacks, take a look at the font example https://github.com/tbleckert/react-select-search/blob/gh-pages/bootstrap.js#L11

**Comment by tbleckert** [comment]
Docs improved! Let me know what you think @sinkcup and close this if satisfied.

**Comment by sinkcup** [comment]
Great!
suggestion: accent support React 0.14, now the notice is "React 0.12 ..." , if user look this page quickly, maybe think this is a old package only support 0.12.

```
Note!
This version support React 0.14
A React 0.12.* supported version can be found in 0.2.* (and below) tagged releases
```

**Comment by tbleckert** [comment]
That's very true, thanks for that. Added now

**Comment by sinkcup** [comment]
:+1:
