### ISSUE TITLE
get wrong search options

### ISSUE THREAD

**Issue by scienfier** [tbleckert/react-select-search#101]
https://react-select-search.com/?path=/story/multiple-select--with-placeholder

When input "hame";I got the below results. 

![image](https://user-images.githubusercontent.com/68145371/87220580-9a094c00-c397-11ea-89fb-5c0bcfe1e15e.png)

I guess it is the fuzzySearch function's problem?

**Comment by scienfier** [comment]
I see. Set the fuse to false,then it matches exactly. But there is one word delay in the search. 

 if I input hame,the hamburger reesult will still be there.

**Comment by tbleckert** [comment]
v3 includes custom filter support, so you can now easily use your own fuzzy search implementation or library if the default is too fuzzy
