### ISSUE TITLE
Select on space key, not enter

### ISSUE THREAD

**Issue by avalsoff** [tbleckert/react-select-search#109]
Very good library, but I need to select option without submitting a form. 
Is there way I can replace enter key to space key?

**Comment by davidangel** [comment]
I had this same issue and solved it by intercepting the`onKeyPress` event in a styled component wrapper:

```jsx
    <StyledSelectSearchWrapper
      onKeyPress={e => {
        e.key === 'Enter' && e.preventDefault();
      }}
    >
      <ReactSelectSearch ... />
    </StyledSelectSearchWrapper>
```
