### ISSUE TITLE
When i do getOptions, i can no longer get the value of the selected item when the user clicks with mouse 

### ISSUE THREAD

**Issue by maidul98** [tbleckert/react-select-search#112]
CodeSandbox Reproduction: https://codesandbox.io/s/react-select-search-bug-forked-xvjfk

You can see in the console that when you select an item with enter key, it prints "hey", but when you click an item it doesn't register it. Would love some help on this bug.

**Comment by andreymoser** [comment]
Hey @maidul98 :) Please take a look on issue #107 - this is issue is duplicated.
