### ISSUE TITLE
mismatch type for getOptions (async) param on v2.0.6

### ISSUE THREAD

**Issue by andreymoser** [tbleckert/react-select-search#117]
Hey @tbleckert 😀 ! 

I have reading the docs, storybook and code and I noticed that `getOptions` type on `v2.0.6` seems to not match each other, as per I have checked it should be `getOptions?: (query:string) => Promise<SelectSearchOption[]>` instead of `getOptions?: (query:string) => Promise<SelectedOption>`. 

I am going to create a PR soon with this suggestion in order to help, please let me know if there is something else there. 🚀

**Comment by tbleckert** [comment]
Good catch! I merged the PR and was included in the latest published patch 2.0.7
