### ISSUE TITLE
Reset option?

### ISSUE THREAD

**Issue by jordibuj** [tbleckert/react-select-search#122]
Is it possible to have a Reset-like option that sets the value to null? 
I can see how to do it with an external button, but users often expect to have this as an option. I just tried adding an item in the Events / Controlled Value example but didn't work... am I missing anything?
```javascript
<SelectSearch
  onChange={setSize}
  value={size}
  placeholder="Select size"
  options={[
    { value: 'small', name: 'Small' },
    { value: 'medium', name: 'Medium' },
    { value: 'large', name: 'Large' },
    { value: null, name: 'Reset'},
  ]}
/>
```

**Comment by manvydasu** [comment]
@jordibuj 
on your **onChange** function (**setSize**) you can just handle that special value
i.e.

```
if (newValue === 'specialValue') {
    // reset state
} else {
    // set new value like usual
}
```

**Comment by jordibuj** [comment]
Than you @manvydasu , it worked perfectly!
