### ISSUE TITLE
Multiselect: when you press enter on option it triggers submit for example.

### ISSUE THREAD

**Issue by agustingabiola** [tbleckert/react-select-search#123]
Thanks for the latest improvements @tbleckert Though I found a regression maybe. When you press enter on an option while doing multi-select, the event bubbles up so adding a preventDefault/stopPropagation should fix this.

**Comment by tbleckert** [comment]
@agustingabiola Thanks and thank you for reporting. I think this is a duplicate of #109 right?

**Comment by agustingabiola** [comment]
> @agustingabiola Thanks and thank you for reporting. I think this is a duplicate of #109 right?

Indeed, I missed that issue while looking for an existing one before reporting. I will close it. Thank you and good day.
