### ISSUE TITLE
Add undefined support for value

### ISSUE THREAD

**Issue by UnclespaceGroup** [tbleckert/react-select-search#127]
In many cases, I need to have an option with a value of undefined in value to reset the field. At this time, a warning appears in the console. Please correct it.

**Comment by manvydasu** [comment]
Can't you use null instead?

**Comment by UnclespaceGroup** [comment]
![image](https://user-images.githubusercontent.com/37845650/96265845-a15f7780-0fce-11eb-9191-ce4becb1032d.png)
Null get same error

**Comment by manvydasu** [comment]
What about this approach?
https://github.com/tbleckert/react-select-search/issues/122

**Comment by UnclespaceGroup** [comment]
okay, many thanks!
