### ISSUE TITLE
Contributors and ideas

### ISSUE THREAD

**Issue by andreymoser** [tbleckert/react-select-search#130]
Hey @tbleckert!

I have found this project when I was researching months ago for a lightweight React component for select and I could notice how incredible it was in the first time I have used it. First of all, congratulations for the awesome work on this project! 👏 

Maybe we could establish an open communication channel for contributors (e.g.: Slack) to express our ideas asynchronously, find out improvements for the component, track tech debts, define the contributing section, gather more contributors, feedbacks and so on. I am open to know what do you think about it. :)

Have a great week and happy coding! :)

**Comment by tbleckert** [comment]
Thanks for your kind words @andreymoser ! Sounds like a good idea. I can setup a Slack channel and we can take it from there, see how it goes. Would love to get more contributors, hard to keep it going as it grows. Good place to discuss the v3 version I'm working on in the next branch.

Happy coding!

**Comment by andreymoser** [comment]
That´s great @tbleckert ! I will be happy to join the slack channel! 💯

**Comment by andreymoser** [comment]
Hey @tbleckert! Just curious, I have seen some work on next branch and I would like to contribute and hear from you some things that you're looking for to achieve in the next version. I have some suggestions but in the first moment it's more important to help you as well. Let's keep in touch! 👍

**Comment by sid-kap** [comment]
Has a Slack channel been set up? I'm also thinking about contributing, and would love to join if it exists

**Comment by tbleckert** [comment]
@sid-kap and @andreymoser I've setup a slack channel but didn't get any further with it because of other things that got in the way. For now you can just send me an email and I'll invite you. Then we can setup up an invitation page.

**Comment by andreymoser** [comment]
hey @tbleckert! Sorry for the delay, my e-mail is andrey@bidicode.com :)
