### ISSUE TITLE
Include full example with style.css in docs

### ISSUE THREAD

**Issue by stephen-farris-jhuapl-edu** [tbleckert/react-select-search#132]
I'm unable to import style.css for some reason (```import 'react-select-search/style.css``` doesn't work), and it would be helpful to see an example in the docs that shows how to properly import style.css. The examples in Storybook are all relative to the project source, and thus not helpful since my code is external to the project.

**Comment by tbleckert** [comment]
@stephen-farris-jhuapl-edu I'm guessing this is related to your other issue. `import 'react-select-search/style.css` as you tried is how it works and should work now with 2.2.1.
