### ISSUE TITLE
style.css not included in installation

### ISSUE THREAD

**Issue by stephen-farris-jhuapl-edu** [tbleckert/react-select-search#133]
```import 'react-select-search/style.css'``` isn't working (it says ```Module not found: Can't resolve 'react-select-search/style.css' in ...```). When I inspected the 'react-select-search' folder in node_modules, style.css isn't there. How do you install style.css? Without it, the select component works great but doesn't look very nice.

**Comment by tbleckert** [comment]
@stephen-farris-jhuapl-edu Must have fallen out when cleaning up the the npm package. The style.css is more of a demo/example on how you can style the component with css (also have this example with CSS modules https://react-select-search.com/?path=/story/custom--css-modules).

But I'll create a patch release including it. Thanks for noticing and reporting.

**Comment by tbleckert** [comment]
@stephen-farris-jhuapl-edu Just published 2.2.1 that includes style.css
