### ISSUE TITLE
Any way to change arrow icon to a search icon?

### ISSUE THREAD

**Issue by sergeyvelichkin** [tbleckert/react-select-search#136]
please

**Comment by anuj0361** [comment]
+1

**Comment by mayckxavier** [comment]
+1

**Comment by IzoldaV** [comment]
You can use a custom renderer to do this. The library has a renderValue property that accepts a function that will render the input field. You can also specify your classname for the select and add a pseudo-element with a search icon for divs that wraps the value-input.
