### ISSUE TITLE
Value is not setting when use getOptions

### ISSUE THREAD

**Issue by konstaner** [tbleckert/react-select-search#161]
It's not working even in storybook example "Async / Fetch".
Focus on field -> input search string -> Select option -> Input value resets.

Screencast: https://monosnap.com/file/eueRqxhHuEvxAMfFOlWJoyxmUyHO0H

**Comment by tbleckert** [comment]
Thanks for the report @konstaner  and sorry for the late reply. This was fixed in v3.0.4.
