### ISSUE TITLE
How to use renderOption?

### ISSUE THREAD

**Issue by TheGP** [tbleckert/react-select-search#164]
There is no source code at https://react-select-search.com/?path=/story/custom--avatar-example

**Comment by LukeV111** [comment]
Did you figure this out @TheGP ?

**Comment by TheGP** [comment]
@LukeV111 Yes: https://react-select.com than u can just search anything and there are a lot of examples on StackOverflow for any question

**Comment by otox-rz** [comment]
Hi guys, I think you should check on [this](https://github.com/tbleckert/react-select-search/blob/24bbf7f76acf0f13f10c5bcdb31becc9a600e970/stories/3-Custom.stories.js#L57)

```

function renderFriend(props, option, snapshot, className) {
    const imgStyle = {
        borderRadius: '50%',
        verticalAlign: 'middle',
        marginRight: 10,
    };

    return (
        <button {...props} className={className} type="button">
            <span><img alt="" style={imgStyle} width="32" height="32" src={option.photo} /><span>{option.name}</span></span>
        </button>
    );
}

export const AvatarExample = () => (
    <SelectSearch
        className="select-search select-search--multiple"
        options={friends}
        renderOption={renderFriend}
        multiple
        search
        filterOptions={fuzzySearch}
        placeholder="Search friends"
    />
);

```


> @LukeV111 Yes: https://react-select.com than u can just search anything and there are a lot of examples on StackOverflow for any question


I think this library has very small package size. We can compare it here

https://bundlephobia.com/scan-results?packages=react-select,react-select-search

**Comment by tbleckert** [comment]
I will improve the storybook as soon as possible, but just a reminder that all code is here on github. All stories/examples can be found here https://github.com/tbleckert/react-select-search/tree/main/stories
