### ISSUE TITLE
npm install the package & get this error for some reason

### ISSUE THREAD

**Issue by bigbadbrad** [tbleckert/react-select-search#168]
./node_modules/react-select-search/dist/esm/SelectSearch.js
Module not found: Can't resolve 'react/jsx-runtime' in '/Users/bradmeinert/Documents/GitHub/fp-client/node_modules/react-select-search/dist/esm'

**Comment by DavidWells** [comment]
I am also seeing this 😅

For some context, this is in older react 16 CRA

```
 "peerDependencies": {
    "react": "^16.0.0"
  },
  "devDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "^3.4.1"
  },
```

**Comment by bigbadbrad** [comment]
Yes I'm using the same react.  I get this error when I simply import the package-

import SelectSearch from 'react-select-search';

**Comment by joeyparis** [comment]
I am also getting this error on react-select-search@2.2.4 with React@^16.13.1

**Comment by icaroscherma** [comment]
As @tbleckert stated on issue #175 :

> @GitanjaliCS I see, version v3 only supports the new JSX transform as of now. How are you transforming jsx right now? Babel?

So in other words, a newer version of React and it's needed or a "manual" JSX transformation is required.
