### ISSUE TITLE
Error when using cjs module

### ISSUE THREAD

**Issue by satanworker** [tbleckert/react-select-search#172]
Hey! Thank you so much for such a useful library. I've found the problem with Next.js if I try to use it out of the box, the compiler gives an error because it's trying to use esm module on the server like so
<img width="1383" alt="Screen Shot 2021-03-03 at 13 44 47" src="https://user-images.githubusercontent.com/11026240/109786495-a42dd280-7c26-11eb-8901-b9610cbc796d.png">
I think the problem is it's trying to use ESM module as the main
if I change package.json main property like this
<img width="532" alt="Screen Shot 2021-03-03 at 13 45 36" src="https://user-images.githubusercontent.com/11026240/109786646-cf182680-7c26-11eb-9a00-31022a1ff946.png">
It compiles successfully, I'm not sure, but I think that is how it suppose to work 
main - points to cjs
module - points to esm
I'm a newbie in open source, so let me know if that was helpful and if you want me to do anything else, thank you for all your work that is truly the best select for react

**Comment by GabrielMochi** [comment]
Same issue.

**Comment by AmyAmy** [comment]
Running into the same issue, created PR.
