### ISSUE TITLE
Typescript: missing type function in `emptyMessage` prop in type `SelectSearchProps`

### ISSUE THREAD

**Issue by marsonparulian** [tbleckert/react-select-search#189]
Version : 3.0.6

**To produce the bug**
Instead of `string`, supply `emptyMessage` (in `SelectSearchProps`) with a function returning a string.
This will make `typescript` compiler complains about incompatible type.

Based on `README.md` `emptyMessage` should accepts parameter a string *or* a function returning a string.

**Solution**
I will create a PR to add a function in type definition file : 
`emptyMessage? : string|(()=>string)`

Thanks.

**Comment by tbleckert** [comment]
Thanks for the fix and report, included in v3.0.7
