### ISSUE TITLE
Scroll menu options on pressing down or up arrow key

### ISSUE THREAD

**Issue by shreyasrh9** [tbleckert/react-select-search#200]
## Problem

If a user presses the down/up array key the option getting highlighted will change but it won't scroll to the highlighted option.

## Solution

If we set a ref to the button tag in the option.js and scroll to the option using ref.current.scrollIntoView(); when the down/up arrow key is pressed.

### Current problem

![ezgif com-gif-maker](https://user-images.githubusercontent.com/29621315/123323621-634e2680-d553-11eb-887f-cdb9e7466b4a.gif)

### Fix

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/29621315/123324282-4534f600-d554-11eb-87f6-32cdf33963cc.gif)

**Comment by tbleckert** [comment]
Fixed in v3.0.8

**Comment by cjadhav** [comment]
Hi Guys,

Like we highlight option using keyboard arrow "up/down" key and select the same using "Enter" key.

Do we have any provision to select option with tab after hightlighting.??

Thanks
