### ISSUE TITLE
add a pagination for search result

### ISSUE THREAD

**Issue by kaiwen1811** [tbleckert/react-select-search#21]
hello, can u add a pagination for search result.

**Comment by tbleckert** [comment]
Hi! Thanks for your suggestion. Not sure if that would be good UX, but might be. I'll let this sit here for a while and see if it gets enough upvotes.

**Comment by hylickipiotr** [comment]
> Hi! Thanks for your suggestion. Not sure if that would be good UX, but might be. I'll let this sit here for a while and see if it gets enough upvotes.

Hi I want to ask if this feature will be available?
