### ISSUE TITLE
State change update fails to change text

### ISSUE THREAD

**Issue by gdsdougherty** [tbleckert/react-select-search#24]
We experienced an issue where changing the state value, that the value prop pointed at, to a blank string would change most aspects of the object, however the search input would not clear until a manual click was performed outside of the element.  Triggering a click via any other means would not cause a refresh, nor would any changes to the element via jquery or javascript.

The only thing that ended up working was by getting a ref to the index object, and calling the __outsideClickHandler manually after changing the value.  On our end we're also running a force update after this, and this is in the callback of the setState that clears the value.

While I've solved the issue on my end, this really doesn't seem like intended behavior, and someone else will likely have this issue.

**Comment by tbleckert** [comment]
Thanks for reporting it! Definitely a bug.

This seems to be the problem https://github.com/tbleckert/react-select-search/blob/master/src/index.js#L117 . Updates from outside of the component through props only causes a refresh when the focus changes.

**Comment by Aeolun** [comment]
Any chance we'll see a fix for this? I thought this dropdown was a lot better than the one I used before, but it's a bit hard to use with this bug.

**Comment by hiphapis** [comment]
Can i know progress this issue?

**Comment by tbleckert** [comment]
@hiphapis Looking at it this today so hoping to have a new version out by tomorrow with this fix and the other stuff in master.

**Comment by tbleckert** [comment]
This has been fixed in v0.9.4, thanks for your patience!
