### ISSUE TITLE
Example Not Working

### ISSUE THREAD

**Issue by spaceComplexitys** [tbleckert/react-select-search#241]
**Describe the bug**
404 not found

**To Reproduce**
1. Go to ReadMe Demo
2. Click on https://react-select-search.com/
3. See error

**Expected behavior**
Shows Not found in the web page

**Comment by thgh** [comment]
Hi, it's broken again:

This site can’t provide a secure connection
react-select-search.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
