### ISSUE TITLE
Search Options Overlapped by Other Elements Below

### ISSUE THREAD

**Issue by ztroop** [tbleckert/react-select-search#247]
Hello! I'm using the latest version of `react-select-search` and I noticed when clicking the search, the options below are overlapped by other elements. I tried overriding `.select_search__select` with `z-index: 999 !important` but it didn't seem to help. Is there anything else I can do?

**Comment by jtmarquez** [comment]
Could you comment on how you were able to solve it? @ztroop

**Comment by ztroop** [comment]
I improved the component hierarchy in the application, which resolved the issue I experienced for this ticket.

**Comment by jtmarquez** [comment]
I was able to solve it too; for some reason using `transform: scale` on a div that contained the search-select messed up with the styles.
