### ISSUE TITLE
Wrong highlight indexing.

### ISSUE THREAD

**Issue by mmuric** [tbleckert/react-select-search#264]
**Describe the bug**
I'm using useSelect to create select box, and I encountered on the problem. When you try to search any word, and after that when you try to select option with up and down key, if you keep pressing down key highlight will disappear. Also, if you start pressing up/down key and try to select an option, it may result in a different selection.

**To Reproduce**
1. Go to your [storybook here](https://react-select-search.com/?path=/story/default--search).
2. In a input type "Bul", it will show 4 options.
3. If you keep pressing down key, highlight will go till the end of the list which is "Syrian Arab Republic", and than it will skip to unknown, or disappear.
4. Also if you select "Bulgaria" selected result will be something like Albania.

**Expected behavior**
I expected that highlight will start over from top. And that I can select option that I want.

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 111.0.5563.110]

**Additional context**
I'm not 100% sure, but I think that in [this line of code](https://github.com/tbleckert/react-select-search/blob/main/src/useSelect.js#L61-L65), instead of passing options, you should pass [something like you return in snapshot](https://github.com/tbleckert/react-select-search/blob/main/src/useSelect.js#L78).

**Comment by jwmann** [comment]
I also have this bug.

If you do a fuzzy search and you find the one you want:
Clicking on the result works as expected.
However, if you use the keys to go down and then press Enter on the result, it will take the index on the results list but grab the index from the options lists.

index 0 from the results are not the same as index 0 from the options.

**Comment by tbleckert** [comment]
Fixed in v4.1.7 by https://github.com/tbleckert/react-select-search/pull/265
