### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by DDushkin** [tbleckert/react-select-search#28]
Hi, in your documentation you said:
/**
 * The options array should contain objects.
 * Required keys are "name" and "value" but you can have and use any number of key/value pairs.
 */
So I added new key value pair to the option object (address: "hello@something")
And I render my options like this (attached screenshot) name, address and image
![image](https://user-images.githubusercontent.com/25999628/48771673-b213ef80-ecca-11e8-9502-77ae3ac6075e.png)
The question is how can I search by address because now it search only in name values

**Comment by tbleckert** [comment]
Hi @DDushkin , sorry for the late reply!

You are on the right path, you just need to configure the search options. You can pass a fuse configuration object like so:

```
const fuse = {
    keys: ['name', 'address'],
    threshold: 0.3,
};

<SelectSearch fuse={fuse} options={...} />
```

**Comment by DDushkin** [comment]
Thank you! It works now :)

**Comment by tbleckert** [comment]
@DDushkin Glad to hear it!
