### ISSUE TITLE
How to autocomplete off

### ISSUE THREAD

**Issue by glinkap** [tbleckert/react-select-search#29]
How to setup autocomplete="off" ?

**Comment by tbleckert** [comment]
Not possible at the moment but a great feature to implement.

**Comment by Darshan-Chauhan** [comment]
@tbleckert  and @glinkap , I think we can close this issue now.

**Comment by tbleckert** [comment]
@Darshan-Chauhan Correct, great work! I've published v0.10.1 that includes your fix for this.
