### ISSUE TITLE
have problem with set default value when options feed from AJAX

### ISSUE THREAD

**Issue by huiman** [tbleckert/react-select-search#35]
please help 
 var options = this.state.LGs
      ? this.state.LGs.map(function(LG) {
          return {
            name: LG.StructName,
            value: LG.StructID
          };
        })
      : [];

    <SelectSearch
            name="LG"
            value={this.state.LG}
            options={options}
            placeholder="Select LG"
          />

I could not set default value.
the error show:

TypeError: this.state is undefined[Learn More] index.js:400
    findByValue 25

  if (!source || source.length < 1) {
-->        findSource = this.state.defaultOptions;
      }

**Comment by abhishekrajawat** [comment]
Same issue with me. Any solution?

**Comment by MWalid** [comment]
Same here

**Comment by tbleckert** [comment]
Fixed in v1
