### ISSUE TITLE
How to make always options open

### ISSUE THREAD

**Issue by javeedrahman** [tbleckert/react-select-search#37]

**Comment by colin-nolan** [comment]
It looks like the only way to achieve "always open" functionality is with `multiple=true`.

What I'm looking for is like the friend selection box on the [example page](http://tbleckert.github.io/react-select-search/) but **not** with multiselect.

**Comment by tbleckert** [comment]
@javeedrahman @colin-nolan So basically the looks of the multiselect but where you can only select one option?

**Comment by colin-nolan** [comment]
Yes :)

**Comment by renanogueira** [comment]
Indeed also :(

**Comment by tbleckert** [comment]
Sorry for the delay on this. I've added a new option in v1.2 that solves this. You can now set `printOptions` to always, to always render the options list.
