### ISSUE TITLE
Keyboard usability issues

### ISSUE THREAD

**Issue by colllin** [tbleckert/react-select-search#4]
When I use the keyboard to select an option (e.g. ArrowDown - ArrowDown - ArrowDown - Enter), the field is blurred.  So then when I push `tab` to get to the next field, nothing is focused, so it focuses on the first field in the page instead of the next field in the page.

![image](https://s3.amazonaws.com/f.cl.ly/items/0C2y2H3x1r340i152V1s/Screen%20Recording%202016-04-27%20at%2009.09%20AM.gif)

I think the best behavior would be to keep the search field focused, select() the text, and close the options dropdown.  This allows the user to see what they selected and `tab` to the next field.  They could also start typing a fresh search immediately, which would overwrite the selected text.  Ideally they could also use the arrow keys to browse the options (which would redisplay the options).

I can accomplish a behavior that's pretty close using the `valueChanged` callback like this:

```
        // Need to set the search field value because otherwise it is cleared when the value changes.
        this.selectSearch.refs.search.value = getSelectedOptionDisplayName();
        this.selectSearch.refs.search.select();
        // Trick the SelectSearch into acting like it was blurred.
        this.selectSearch.onBlur();
        var $input = $(ReactDOM.findDOMNode(this.selectSearch.refs.search));
        // If it's the tab key, return true to let the event continue. Otherwise trick the selectSearch to act like it was focused.
        $input.one('keydown', (event) => (event.which == 9 ? true : this.selectSearch.onFocus()));
```

Which gives this behavior:

![image](https://s3.amazonaws.com/f.cl.ly/items/3Z2J3t1H3h0D2D1F033k/Screen%20Recording%202016-04-27%20at%2010.17%20AM.gif)

What do you think?  Should this be the built-in behavior?  How could I accomplish this in a less hacky way?

**Comment by colllin** [comment]
Fixed GIFs.

**Comment by tbleckert** [comment]
This should definitely be built in, thanks for reporting this. I will take a look first thing tomorrow and get back to you during the day. Nice hack btw.

**Comment by tbleckert** [comment]
I'm working on this but taking a little longer than expected, found a couple of other problems as well that needs to be fixed.

**Comment by colllin** [comment]
Thanks for the update. Looking forward to this.

Collin
720-987-6472

**Comment by tbleckert** [comment]
Sorry for the delay, wish I had more time to work on this :(

I've just released a new version. The new version includes improved focus management and other great stuff. You can now tab through the controls but what's still missing is that it doesn't put focus back on the search field after you have selected an option. Will release a patch in a day or two.

**Comment by sontek** [comment]
@tbleckert You still working on this one?

**Comment by tbleckert** [comment]
Fixed in v1
