### ISSUE TITLE
Searching large data. 

### ISSUE THREAD

**Issue by JetCrazy** [tbleckert/react-select-search#45]
I have an Select with about 2,900 names. The search is not refined. 
![image](https://user-images.githubusercontent.com/33587293/64058244-5ab68000-cb76-11e9-98e5-717c0f094482.png)
![image](https://user-images.githubusercontent.com/33587293/64058249-5f7b3400-cb76-11e9-96f7-684831e6b826.png)
If I backspace the search also gets really confused and messes up.

**Comment by tbleckert** [comment]
Hi! You can try tweaking the fuzzy search settings to be more strict. The default is a threshold of 0.3

```
fuse: {
    keys: ['name'],
    threshold: 0.3
}
```

You can check https://fusejs.io/ for complete set of options you can pass in. Hope that helps.

**Comment by JetCrazy** [comment]
> Hi! You can try tweaking the fuzzy search settings to be more strict. The default is a threshold of 0.3
> 
> ```
> fuse: {
>     keys: ['name'],
>     threshold: 0.3
> }
> ```
> 
> You can check https://fusejs.io/ for complete set of options you can pass in. Hope that helps.

Thanks for reply. Changing fuse settings in the dist and regular package did not work. the search is still not good. I tried with just fuse on there site and it gave me the expected output

**Comment by tbleckert** [comment]
@JetCrazy You can pass the fuse options as a prop to the select. You don't need to rebuild the package.

```jsx
import SelectSearch from 'react-select-search';

<SelectSearch fuse={{ threshold: 0.3 }} />
```

**Comment by JetCrazy** [comment]
@tbleckert after taking a few weeks break from coding and finally getting back into everything and getting the same problem after some investigation I narrowed it down to the renderOptions(), 
![image](https://user-images.githubusercontent.com/33587293/68421889-1e526200-016d-11ea-8229-d152a615a6dc.png)
this is the response fuse responds with yet the output on my page is:
![image](https://user-images.githubusercontent.com/33587293/68421950-417d1180-016d-11ea-8e75-edeae767ff03.png)

**Comment by tbleckert** [comment]
@JetCrazy Lots of refactoring and improvement went into the v1 and v2 releases. Can you check if this is still an issue for you, and if so, can you create a test case on codesandbox?
