### ISSUE TITLE
PropTypes not working properly

### ISSUE THREAD

**Issue by JanKaifer** [tbleckert/react-select-search#46]
I have forgottent to specify `options`.

## Expected:

propTypes would say that options are required.

## Actual:

```
   FlattenOptions.js:10 Uncaught TypeError: Cannot read property 'forEach' of undefined
```

**Comment by Darshan-Chauhan** [comment]
@JanKaifer , can you please provider reproduction?

**Comment by JanKaifer** [comment]
Just ommit `options` and you should get this error.

**Comment by tbleckert** [comment]
@JanKaifer Thanks for reporting. The options property is now required and should throw an error in dev mode.
