### ISSUE TITLE
Wrong selection when option's value is zero

### ISSUE THREAD

**Issue by Arnique** [tbleckert/react-select-search#53]
Selecting an option with zero as value triggers the selection of the first option(index 0) e.g

```
const options = [
    { name: '100%', value: 100 },
    { name: '50%', value: 50 },
    { name: 'None', value: 0}
]

<SelectSearch
     name="rate"
     options={options}
 />
```
I'm assuming there's truthy check for null values in the code that gets tripped when it encounters a zero.

**Comment by tbleckert** [comment]
@Arnique Good catch and thanks for reporting. I'll fix it as soon as I can

**Comment by tbleckert** [comment]
Fixed in v1
