### ISSUE TITLE
How to customise the chevron icon for the dropdown?

### ISSUE THREAD

**Issue by subhendukundu** [tbleckert/react-select-search#54]
Is there a way to change/pass the chevron icon as an HTML element? I want to replace it with a svg icon I have. How do I do that?

**Comment by tbleckert** [comment]
@subhendukundu This is something I'm working on. As of now, there's very limited options regarding changing the markup. Right now you have two options. The first is you can use your svg as a background image using CSS. The other option is to extend the `SelectSearch` class and override the `renderSearchField` method to render your own HTML.

**Comment by TapanChoudhary** [comment]
Hi @subhendukundu  You can do this by updating the css file. 
Replace content property with your desired icon.

.select-search-box::after {
        font-family: fontawesome;
        content: **_"\f0d7"_** ;
        position: absolute;
        top: 0;
        right: 0;
        width: 40px;
        text-align: center;
        line-height: 50px;
        color: #222f3e;
        z-index: 1;
    }

[Here](https://fontawesome.com/icons?d=gallery&q=dropdown) you can find the icons and [here](https://fontawesome.com/icons/caret-down?style=solid) you can get the icon code.

**Comment by MWalid** [comment]
Any updates on this issue?

**Comment by tbleckert** [comment]
@MWalid Yeah, sorry, been a few busy months. I'm working on a rewrite in the `next` branch. You can try it out right now with `npm i react-select-search@next`, although I haven't written a migration guide yet.

In the new version you get more control in the rendering callbacks and you can also use it in headless mode using hooks to fully control the rendering. I'll update this issue once it's in the master branch and ready for release. You can also track the progress here #61

**Comment by tbleckert** [comment]
Fixed in v1

**Comment by MWalid** [comment]
Thank you @tbleckert, will give it another try.
