### ISSUE TITLE
Comparison with react-select

### ISSUE THREAD

**Issue by dandv** [tbleckert/react-select-search#57]
Hi, I was looking for a React select component, and found this library. Thanks for publishing it!

Would you be able to compare it with some of the other React select libraries? How would a developer choose between it, and [react-select](https://github.com/JedWatson/react-select) for example?

**Comment by tbleckert** [comment]
Hi @dandv !

react-select has a lot more features whilst react-select-search aims at simply being a drop-in replacement for select boxes. So it really depends on what you need. If all you need is a searchable selectbox and you care about bundle size, then I suggest you give us a try. If you need a feature rich select component with a large community behind it I would go with react-select.

I'm glad you asked and let me know if I can answer some questions you might have.
