### ISSUE TITLE
Warning: Encountered two children with the same key, `[object Object]-option`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.     in ul (created by SelectSearch)     in div (created by SelectSearch)     in div (created by SelectSearch)

### ISSUE THREAD

**Issue by aTrueSeeker** [tbleckert/react-select-search#69]
THis happens when i give value in options as JSON object

**Comment by sjw441500** [comment]
same issue

**Comment by sjw441500** [comment]
you may add a 'value' attribute to each of your data items.

**Comment by sknutsonsf** [comment]
I am still seeing this message using a three-level structure.  Everything has a unique value.  Here is an example of the options:

[
  {
    "name": "My Mountain",
    "value": "ranch_854",
    "type": "group",
    "items": [
      {
        "name": "East Almonds",
        "value": "block_3332",
        "type": "group",
        "items": [
          {
            "name": "East Almonds (2020 Season)",
            "value": "2679"
          }
        ]
      },
      {
        "name": "Pistachios",
        "value": "block_3333",
        "type": "group",
        "items": [
          {
            "name": "Pistachios (A) (2020 Season)",
            "value": "2680"
          },
          {
            "name": "Pistachios (B) (2020 Season)",
            "value": "2681"
          }
        ]
      },
    ]
  },
  }

**Comment by tbleckert** [comment]
@sknutsonsf I can not reproduce this in v1.2. Would you be able to check if this is still an issue? Groups uses a unique group ID for the key and options uses their value as the key. Option values has to be unique for other reasons than this.
