### ISSUE TITLE
Backspace doesn't clear options properly

### ISSUE THREAD

**Issue by aethelz** [tbleckert/react-select-search#71]
v1.0.2 does not properly resets option list on backspace before sending it to fuse.

![Peek 2020-03-18 19-33](https://user-images.githubusercontent.com/10677343/76984067-65d4d000-694f-11ea-928e-dabdef2e1c1d.gif)

Minimal reproducible case based on live-demo example code:
https://stackblitz.com/edit/react-7u9dx3

**Comment by aethelz** [comment]
It seems that using `FlattenOptions(defaultOptions)` instead of `flat` here fixes it, but it might me a crude solution to it:

https://github.com/tbleckert/react-select-search/blob/master/src/useSelect.js#L80

**Comment by tbleckert** [comment]
Issue has been fixed. See comment in PR for more info
