### ISSUE TITLE
A way to set a maximum display value for search boxes.

### ISSUE THREAD

**Issue by TomCaserta** [tbleckert/react-select-search#8]
Currently I have a list of 800 items I wish to be able to fuzzy search. The issue arises that this of course is very slow to render and makes it generally sluggish. 

I was wondering if there was a way to set a maximum amount of items to render at once. Of course this will mean a user will have to start typing first to filter through the results but it should mean it renders faster.

Thanks

**Comment by tbleckert** [comment]
I will take a look at the performance problem but a limit setting sounds like a good idea. Thanks! Feel free to submit PRs if you feel like it, all help is appreciated.

**Comment by matheus-garcia** [comment]
was this implemented?

**Comment by khughitt** [comment]
Did you end up adding an explicit mechanism to limit the number of items?

I checked the docs but didn't see anything along these lines.

**Comment by khughitt** [comment]
Nm, found the relevant change.

In case it helps anyone else, here is the relevant example: https://github.com/tbleckert/react-select-search/blob/1a3f24ae2225a2555dd623b28a9d9a9d9b48a16f/stories/0-Single.stories.js#L95

The basic solution is to modify `filterOptions` to include a call to `.slice(0, n)` on the returned result.
