### ISSUE TITLE
renderOption renderValue won't stop re rendering

### ISSUE THREAD

**Issue by JoueBien** [tbleckert/react-select-search#83]
Un-able to set options and use the custom render options because the options are constantly getting re-drawn. This causes the scroll box  force relocate to the top after the scroll event has finished and for for the options to become un-clickable

importing the select field using 
```
import SelectSearch from 'react-select-search/dist/cjs'
```

**Comment by JoueBien** [comment]
At the moment the issue looks like it has been introduced after 
commit e799dcd9104309096c4c2a38bc21e86bfe00703a

You can get around this issue using a manual install of an older build
```
npm install --save https://github.com/tbleckert/react-select-search.git#e799dcd9104309096c4c2a38bc21e86bfe00703a
```

**Comment by tbleckert** [comment]
@JoueBien Which version are you running? v2.x or v1.x?

**Comment by JoueBien** [comment]
> @JoueBien Which version are you running? v2.x or v1.x?

I was running 2.x latest. I've had to drop back to the last 1.0. 2 build because of this issue.

**Comment by tbleckert** [comment]
@JoueBien Ok, I'll take a look. Please create a reproducible test case on codesandbox if you have the time.
