### ISSUE TITLE
View Config getter callback for component 'input' must be a function (recieved undefined)

### ISSUE THREAD

**Issue by NawazKhanMd** [tbleckert/react-select-search#84]
![image](https://user-images.githubusercontent.com/15027672/82280262-1ab95680-99ac-11ea-94f0-e60dfa3cf65b.png)

Just copy pasted the demo code its giving error

![image](https://user-images.githubusercontent.com/15027672/82280392-69ff8700-99ac-11ea-90c8-8950335f3955.png)
![image](https://user-images.githubusercontent.com/15027672/82280501-9d421600-99ac-11ea-961a-1b9b055e2ef5.png)

**Comment by tbleckert** [comment]
@NawazKhanMd This component is unfortunately not built for React Native. You could use the the hook though and build your own view components.
