### ISSUE TITLE
 closeOnSelect is not working on multiple search on-focus

### ISSUE THREAD

**Issue by matheus-garcia** [tbleckert/react-select-search#87]
Passing the property  closeOnSelect={false} is not keeping the modal open.

i'm using it like this:

```
<SelectSearch
    options={optionsUnidades}
    multiple 
   search
   closeOnSelect={false}
   printOptions="on-focus"
   placeholder="Associe as Unidades *"
 />
```

**Comment by tbleckert** [comment]
Thanks for reporting, I'll take a look during the day

**Comment by agustingabiola** [comment]
@tbleckert Hi, first of all awesome library. Have you been able to take a look at this?

**Comment by tbleckert** [comment]
Sorry for the delay. Fixed in 2.0.6

**Comment by agustingabiola** [comment]
Thanks a lot @tbleckert , just tried it and working fine.

**Comment by tbleckert** [comment]
@agustingabiola Awesome!
